<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>14</LangVersion>
    <AssemblyTitle>PluginSelect</AssemblyTitle>
    <Company>Nytra</Company>
    <Product>PluginSelect</Product>
    <Copyright>Copyright © Nytra 2026</Copyright>
    <AssemblyVersion>1.0.2</AssemblyVersion>
    <FileVersion>1.0.2</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Resonite.GameLibs" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Resonite\rml_libs\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="ResoniteHotReloadLib">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Resonite\rml_libs\ResoniteHotReloadLib.dll</HintPath>
    </Reference>
    <Reference Include="ResoniteModLoader">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Resonite\Libraries\ResoniteModLoader.dll</HintPath>
    </Reference>
  </ItemGroup>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="C:\Program Files (x86)\Steam\steamapps\common\Resonite\rml_mods\HotReloadMods" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="C:\Program Files (x86)\Steam\steamapps\common\Resonite\rml_mods" />
  </Target>
</Project>